### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by cxlpun** [Robswc/tradingview-webhooks-bot#14]
This is the error i am getting could you assist?

```
SyntaxError: invalid syntax
127.0.0.1 - - [03/Feb/2020 14:21:52] "POST /webhook HTTP/1.1" 500 -
Traceback (most recent call last):
  File "C:\Users\user\.virtualenvs\tvwebhooks-2LK2msMJ\lib\site-packages\flask\app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\user\.virtualenvs\tvwebhooks-2LK2msMJ\lib\site-packages\flask\app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\user\.virtualenvs\tvwebhooks-2LK2msMJ\lib\site-packages\flask\app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\user\.virtualenvs\tvwebhooks-2LK2msMJ\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\user\.virtualenvs\tvwebhooks-2LK2msMJ\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\user\.virtualenvs\tvwebhooks-2LK2msMJ\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\user\.virtualenvs\tvwebhooks-2LK2msMJ\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\user\.virtualenvs\tvwebhooks-2LK2msMJ\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\user\.virtualenvs\tvwebhooks-2LK2msMJ\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\user\.virtualenvs\tvwebhooks-2LK2msMJ\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\user\Google Drive\Python\tvwebhooks\main.py", line 20, in webhook
    data = parse_webhook(request.get_data(as_text=True))
  File "C:\Users\user\Google Drive\Python\tvwebhooks\actions.py", line 13, in parse_webhook
    data = ast.literal_eval(webhook_data)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\ast.py", line 46, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
File "<unknown>", line 1
    BTCUSD, 1 Moving Up 0.01 in 1 bars
                   ^
SyntaxError: invalid syntax
```

**Comment by cxlpun** [comment]
I found the issue i needed my own custom comment in each alert as it couldn't present plain text.
